services:
    app:
        build: .
        container_name: "Task-Manager"
        networks:
        - "Task-Manager-network"
        env_file:
         - .env
        depends_on: 
            db:
                condition: service_healthy
    db:
        image: postgres:17 
        container_name: "postgres-db"
        networks:
        - "Task-Manager-network"
        env_file:
         - .env
        volumes:
         - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
         - Task-Manager-Volume:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s 
    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
         - "80:80"
        volumes:
         - ./nginx/nginx.config:/etc/nginx/nginx.conf:ro
        depends_on:
            app:
                condition: service_started
        networks:
         - Task-Manager-network
networks:
    "Task-Manager-network":
volumes:
    "Task-Manager-Volume":