name: CI/CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    name: Build, Push and Deploy
    runs-on: ubuntu-latest  

    env:
      AWS_REGION: eu-north-1
      AWS_ACCOUNT_ID: 883291274628
      IMAGE_TAG: ${{ github.sha }}

      APP_REPOSITORY: task-manager-app-ecr
      POSTGRES_REPOSITORY: task-manager-postgres
      NGINX_REPOSITORY: nginx-ecr

      CLUSTER_NAME: TaskManager02
      SERVICE_NAME: task-manager02-service-nxu3jehx
      TASK_DEFINITION: task-definition.json

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        
      - name: Build App Image
        run:  docker build --pull -t $APP_REPOSITORY:$IMAGE_TAG .

      - name: Build PostgreSQL Image
        run:  docker build --pull -t $POSTGRES_REPOSITORY:$IMAGE_TAG ./database
      
      - name: Build Nginx Image
        run: docker build -t $NGINX_REPOSITORY:$IMAGE_TAG ./nginx

      - name: Install snyk cli
        run: npm install -g snyk
      
      - name: Authenticate snyk
        run:  snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Verify Docker Image
        run: docker images

      - name: Verify Snyk
        run: snyk whoami

      - name: Scan App image
        run:  snyk container test $APP_REPOSITORY:$IMAGE_TAG   --policy-path=.snyk --severity-threshold=high  --exclude-base-image-vulns --json > app-snyk-report.json || true

      - name: Scan Postgresql image
        run: snyk container test $POSTGRES_REPOSITORY:$IMAGE_TAG --severity-threshold=high --json > postgresql-snyk-report.json || true

      - name: Scan nginx image
        run: snyk container test $NGINX_REPOSITORY:$IMAGE_TAG --severity-threshold=high --json > nginx-snyk-report.json || true
      - name: Upload Snyk Reports
        uses: actions/upload-artifact@v4
        with:
         name: snyk-reports
         path: |
           *-snyk-report.json
      

      - name: Send Email On Failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465

          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}

          subject: "Snyk Security Scan Failed"

          body: |
            Docker security scan failed.
           
            Repository:
            ${{ github.repository }}

            Check report:
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

          to: usman328ghani@gmail.com
          from: usman328ghani@gmail.com
    

      - name: Tag App Image
        run: docker tag $APP_REPOSITORY:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$APP_REPOSITORY:$IMAGE_TAG

      - name: Push App Image
        run: docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$APP_REPOSITORY:$IMAGE_TAG


      

      - name: Tag PostgreSQL Image
        run: docker tag $POSTGRES_REPOSITORY:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$POSTGRES_REPOSITORY:$IMAGE_TAG

      - name: Push PostgreSQL Image
        run: docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$POSTGRES_REPOSITORY:$IMAGE_TAG

      

      - name: Tag Nginx Image
        run: docker tag $NGINX_REPOSITORY:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$NGINX_REPOSITORY:$IMAGE_TAG

      - name: Push Nginx Image
        run: docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$NGINX_REPOSITORY:$IMAGE_TAG

      

      - name: Update App Image
        id: app-task
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ env.TASK_DEFINITION }}
          container-name: App
          image: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.APP_REPOSITORY }}:${{ env.IMAGE_TAG }}

      - name: Update PostgreSQL Image
        id: postgres-task
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ steps.app-task.outputs.task-definition }}
          container-name: postgres-db
          image: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.POSTGRES_REPOSITORY }}:${{ env.IMAGE_TAG }}

      - name: Update Nginx Image
        id: nginx-task
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ steps.postgres-task.outputs.task-definition }}
          container-name: nginx
          image: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.NGINX_REPOSITORY }}:${{ env.IMAGE_TAG }}

      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.nginx-task.outputs.task-definition }}
          cluster: ${{ env.CLUSTER_NAME }}
          service: ${{ env.SERVICE_NAME }}
          wait-for-service-stability: true